version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-214-211-47.compute-1.amazonaws.com
            port: '5432'
            database: d83h3ra2uddv3
            ssl: true
            user: jykjgifjgusnpm
            password: e915ffbed04d31e24ce4548916c746f3e99e3cd189b719ac397a14e6ecffe8d0
            migrations: true